/* Usuarios 
***************************************************/
INSERT INTO pf_usuarios (nombre, username, edad, genero, foto, correo, contrasenia) VALUES ('Jesus Nzatet', 'minijisus', 2000, 'M','foto.jpg', 'jisus@gmail.com', '12345');
INSERT INTO pf_usuarios (nombre, username, edad, genero, foto, correo, contrasenia) VALUES ('Jesus Nzatet', 'minijisus', 2000, 'M','foto.jpg', 'jisus@gmail.com', '12345');

/* Sitios 
***************************************************/
INSERT INTO pf_sitios (nombre, categoria, ubicacion, descripcion, lat, longitud) VALUES ('Paris', 'Ciudad', 'Paris', 'Paris, la capital de Francia, es una importante ciudad europea y un centro mundial del arte, la moda, la gastronomia y la cultura. Su paisaje urbano del siglo XIX está entrecruzado por amplios bulevares y el rio Sena. Aparte de estos hitos, como la Torre Eiffel y la catedral gotica de Notre Dame del siglo XII, la ciudad es famosa por su cultura del cafe y las tiendas de moda de diseniador a lo largo de la calle Rue du Faubourg Saint-Honore.', 48.8667, 2.3333);
INSERT INTO pf_sitios (nombre, categoria, ubicacion, descripcion, lat, longitud) VALUES ('Playa del Carmen', 'Playa,', 'Quintana Roo', 'Playa del Carmen es considerado el Corazon de la Riviera Maya y por tal motivo no puedes irte de aqui sin conocer uno de los lugares turisticos de Mexico más famosos de esta zona. Esta playa se ubica en la cabecera del municipio de Solidaridad en Quintana Roo, al sureste del pais.', 20.6274,  -87.07987);
INSERT INTO pf_sitios (nombre, categoria, ubicacion, descripcion, lat, longitud) VALUES ('Chichen Itzá', 'Arquitectura', 'Yucatán', 'Ubicado al norte de la Peninsula de Yucatán, podrás encontrar Chichen Itzá, la ciudad mexicana más famosa del mundo y la segunda zona arqueologica más visitada. Se encuentra a una hora en carro de la ciudad de Merida y es el lugar perfecto para conocer la cultura e historia azteca. Además, fue nombrado Patrimonio Cultural de la Humanidad en 1988.', 48.8667, 2.3333);
INSERT INTO pf_sitios (nombre, categoria, ubicacion, descripcion, lat, longitud) VALUES ('Riviera Maya', 'Playa,', 'Quintana Roo', 'La Riviera Maya se extiende desde 36 kilometros al sur de Cancún y termina en el poblado conocido como Punta Allen, al sur de Quintana Roo. En ella encontrarás una gran variedad de atracciones como hermosas islas de arenas blancas, arrecifes, parques nuevos, lagunas y rios.', 48.8667, 2.3333);
INSERT INTO pf_sitios (nombre, categoria, ubicacion, descripcion, lat, longitud) VALUES ('Guanajuato', 'Ciudad', 'Guanaj​​uato', 'Ubicada en la region centronorte del pais, definitivamente Guanajuato es uno de los lugares hermosos de Mexico. Una de las principales razones por la cual tienes que ir a esta ciudad antes de que termine 2019, es su arquitectura: muchas de sus calles y lugares son Patrimonios de la Humanidad.', 21.01858, -101.2591);
INSERT INTO pf_sitios (nombre, categoria, ubicacion, descripcion, lat, longitud) VALUES ('Palenque', 'Arquitectura', 'Chiap​as', 'Ubicado al noroeste del estado de Chiapas y a unas tres horas en carro de la Ciudad Capital se encuentra Palenque. Esta localidad es uno de los lugares para vacacionar en Mexico más destacados ya que muy cerca se encuentra una de las zonas arqueologicas más importantes de la cultura maya.', 48.8667, 2.3333);
INSERT INTO pf_sitios (nombre, categoria, ubicacion, descripcion, lat, longitud) VALUES ('El lago Moraine', 'Lago', 'Alberta', 'El segundo de nuestros lugares imprescindibles que ver en Canadá es el lago Moraine, probablemente uno de los más bonitos que puedas ver jamás, asi como una de las estampas más fotografiadas. Situado en el Parque Nacional Banff de Alberta, ocupa una superficie total de medio kilometro cuadrado y es alimentado por medio de un glaciar que dota a las aguas del lago de un hermoso y llamativo color azul. Se encuentra, además, rodeado de montanias escarpadas de más de 3.000 metros de altura y bosques de coniferas, pertenecientes al Valle de los Diez Picos.', 51.321742, -116.186005);
INSERT INTO pf_sitios (nombre, categoria, ubicacion, descripcion, lat, longitud) VALUES ('Parque Nacional Manuel Antonio', 'Selva', 'Provincia de Puntarenas', 'El pequenio gran pulmon de la costa costarricense es llamado el Parque Nacional Manuel Antonio y cerca de el se puede conseguir el poblado de Quepos.', 48.8667, 2.3333);

/* Opiniones
 ***************************************************/
INSERT INTO pf_opiniones (idSitio, idUsuario, opinion, calificacion) VALUES (9,2,'Muy bonito lugar, recomendado para toda la familia',4);
INSERT INTO pf_opiniones (idSitio, idUsuario, opinion, calificacion) VALUES (9,1,'Mus sucio el lugar, no voy otra vez',1);
INSERT INTO pf_opiniones (idSitio, idUsuario, opinion, calificacion) VALUES (9,2,'Ya fui dos veces y hasta remodelaron el lugar',5);
INSERT INTO pf_opiniones (idSitio, idUsuario, opinion, calificacion) VALUES (13, 2, 'Está hermoso, nunca habia salido del pais, me encanto estar con mi ruka', 5)

