/* Sitios */
INSERT INTO pf_sitios (nombre, categoría, ubicación, descripción, lat, longitud) VALUES ('París', 'Ciudad', 'París', 'París, la capital de Francia, es una importante ciudad europea y un centro mundial del arte, la moda, la gastronomía y la cultura. Su paisaje urbano del siglo XIX está entrecruzado por amplios bulevares y el río Sena. Aparte de estos hitos, como la Torre Eiffel y la catedral gótica de Notre Dame del siglo XII, la ciudad es famosa por su cultura del café y las tiendas de moda de diseñador a lo largo de la calle Rue du Faubourg Saint-Honoré.', 48.8667, 2.3333);
INSERT INTO pf_sitios (nombre, categoría, ubicación, descripción, lat, longitud) VALUES ('Playa del Carmen', 'Playa,', 'Quintana Roo', 'Playa del Carmen es considerado el Corazón de la Riviera Maya y por tal motivo no puedes irte de aquí sin conocer uno de los lugares turísticos de México más famosos de esta zona. Esta playa se ubica en la cabecera del municipio de Solidaridad en Quintana Roo, al sureste del país.', 20.6274,  -87.07987);
INSERT INTO pf_sitios (nombre, categoría, ubicación, descripción, lat, longitud) VALUES ('Chichén Itzá', 'Arquitectura', 'Yucatán', 'Ubicado al norte de la Península de Yucatán, podrás encontrar Chichén Itzá, la ciudad mexicana más famosa del mundo y la segunda zona arqueológica más visitada. Se encuentra a una hora en carro de la ciudad de Mérida y es el lugar perfecto para conocer la cultura e historia azteca. Además, fue nombrado Patrimonio Cultural de la Humanidad en 1988.', 48.8667, 2.3333);
INSERT INTO pf_sitios (nombre, categoría, ubicación, descripción, lat, longitud) VALUES ('Riviera Maya', 'Playa,', 'Quintana Roo', 'La Riviera Maya se extiende desde 36 kilómetros al sur de Cancún y termina en el poblado conocido como Punta Allen, al sur de Quintana Roo. En ella encontrarás una gran variedad de atracciones como hermosas islas de arenas blancas, arrecifes, parques nuevos, lagunas y ríos.', 48.8667, 2.3333);
INSERT INTO pf_sitios (nombre, categoría, ubicación, descripción, lat, longitud) VALUES ('Guanajuato', 'Ciudad', 'Guanaj​​uato', 'Ubicada en la región centronorte del país, definitivamente Guanajuato es uno de los lugares hermosos de México. Una de las principales razones por la cual tienes que ir a esta ciudad antes de que termine 2019, es su arquitectura: muchas de sus calles y lugares son Patrimonios de la Humanidad.', 21.01858, -101.2591);
INSERT INTO pf_sitios (nombre, categoría, ubicación, descripción, lat, longitud) VALUES ('Palenque', 'Arquitectura', 'Chiap​as', 'Ubicado al noroeste del estado de Chiapas y a unas tres horas en carro de la Ciudad Capital se encuentra Palenque. Esta localidad es uno de los lugares para vacacionar en México más destacados ya que muy cerca se encuentra una de las zonas arqueológicas más importantes de la cultura maya.', 48.8667, 2.3333);
INSERT INTO pf_sitios (nombre, categoría, ubicación, descripción, lat, longitud) VALUES ('El lago Moraine', 'Lago', 'Alberta', 'El segundo de nuestros lugares imprescindibles que ver en Canadá es el lago Moraine, probablemente uno de los más bonitos que puedas ver jamás, así como una de las estampas más fotografiadas. Situado en el Parque Nacional Banff de Alberta, ocupa una superficie total de medio kilómetro cuadrado y es alimentado por medio de un glaciar que dota a las aguas del lago de un hermoso y llamativo color azul. Se encuentra, además, rodeado de montañas escarpadas de más de 3.000 metros de altura y bosques de coníferas, pertenecientes al Valle de los Diez Picos.', 51.321742, -116.186005);
INSERT INTO pf_sitios (nombre, categoría, ubicación, descripción, lat, longitud) VALUES ('Parque Nacional Manuel Antonio', 'Selva', 'Provincia de Puntarenas', 'El pequeño gran pulmón de la costa costarricense es llamado el Parque Nacional Manuel Antonio y cerca de él se puede conseguir el poblado de Quepos.', 48.8667, 2.3333);

/* Opiniones
 ***************************************************/
INSERT INTO pf_opiniones (idSitio, idUsuario, opinión, calificación) VALUES (9,2,'Muy bonito lugar, recomendado para toda la familia',4);
INSERT INTO pf_opiniones (idSitio, idUsuario, opinión, calificación) VALUES (9,1,'Mus sucio el lugar, no voy otra vez',1);
INSERT INTO pf_opiniones (idSitio, idUsuario, opinión, calificación) VALUES (9,2,'Ya fui dos veces y hasta remodelaron el lugar',5);

